package View;

import Controller.CTRLDistrict;
import Controller.CTRLEntity;
import Model.SamplingsiteDAO;


/**
 *
 * @author chava
 */
public class Account extends javax.swing.JDialog {

    CTRLEntity CE = new CTRLEntity();
    CTRLDistrict CD =new CTRLDistrict();
    /**
     * Creates new form Reporte
     */
    public Account(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); 
        this.setLocationRelativeTo(null);
        this.EntityCBX();
        this.DistricCBX();
    }
    

    public void EntityCBX(){
        this.CE.loadEntity(cbxEntityReport);
        
    }
    
    public void DistricCBX(){
        this.CD.loadDistrict(cbxDistrictReport);
    }
    
    public void selecSiteDistrict(){
        this.CD.showSamplingsitesForSelectedDistrict(cbxDistrictReport, jTextAreaDistrct);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReportNacientes = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDistrct = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        cbxDistrictReport = new javax.swing.JComboBox<>();
        jButtonSiteDIstrict = new javax.swing.JButton();
        jButtonMostrarEntity = new javax.swing.JButton();
        cbxEntityReport = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reportes");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Nacientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jTextAreaReportNacientes.setColumns(20);
        jTextAreaReportNacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaReportNacientes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReportNacientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 470, 440));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jTextAreaDistrct.setColumns(20);
        jTextAreaDistrct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaDistrct.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDistrct);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 430, 440));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 102));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, -1, -1));

        cbxDistrictReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxDistrictReport.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Distrito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.add(cbxDistrictReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 200, 60));

        jButtonSiteDIstrict.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSiteDIstrict.setText("Stios de muestreos");
        jButtonSiteDIstrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiteDIstrictActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSiteDIstrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 160, 30));

        jButtonMostrarEntity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMostrarEntity.setText("Mostrar");
        jButtonMostrarEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarEntityActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMostrarEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 90, 40));

        cbxEntityReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEntityReport.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Entidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxEntityReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntityReportActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEntityReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, 60));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Nacientes");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1Report.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1200, 647));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
       // Administrador Adm = new Administrador();
       // Adm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxEntityReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntityReportActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxEntityReportActionPerformed

    private void jButtonMostrarEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarEntityActionPerformed
        // TODO add your handling code here:
         String selectedEntityName = cbxEntityReport.getSelectedItem().toString();

    // Ejecutamos el método para mostrar las nacientes
    CE.showNacientesForSelectedEntity(cbxEntityReport, jTextAreaReportNacientes);
    }//GEN-LAST:event_jButtonMostrarEntityActionPerformed

    private void jButtonSiteDIstrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiteDIstrictActionPerformed
        // TODO add your handling code here:
        this.selecSiteDistrict();
    }//GEN-LAST:event_jButtonSiteDIstrictActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxDistrictReport;
    private javax.swing.JComboBox<String> cbxEntityReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonMostrarEntity;
    private javax.swing.JButton jButtonSiteDIstrict;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDistrct;
    private javax.swing.JTextArea jTextAreaReportNacientes;
    // End of variables declaration//GEN-END:variables
}
