package View;

import Controller.CTRLFlowMeasurement;
import Controller.CTRLNascent;
import Controller.CTRLSamplingsite;
import Controller.CTRLUser;
import Model.CantonDAO;
import Model.ProvinceDAO;



public class Administrator extends javax.swing.JFrame {

    CTRLUser CU = new CTRLUser();
    CTRLNascent CN = new CTRLNascent();
    CTRLSamplingsite CS = new CTRLSamplingsite();
    CTRLFlowMeasurement CF = new CTRLFlowMeasurement();
    ProvinceDAO CP = new ProvinceDAO();
    CantonDAO CC = new CantonDAO();
    private int entity_id;

    public Administrator(int entity_id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.entity_id = entity_id;
        this.loadDataUser();
        this.loadDataFlow();
        this.loadDataNascent();
        this.loadDataSites();
        this.cbxEntity();
        this.cbxRoles();
        this.cbxsProvinces();
        this.cbxsNascent();
        this.cbxSampling();
    }
    
    private void loadDataUser() {
        this.CU.loadDataUserAdmin(tblUsers, entity_id);
    }

    private void loadDataNascent() {
        this.CN.loadDataUserAdmin(tblNascent, entity_id);
    }

    private void loadDataSites() {
        this.CS.loadDataAdmin(tblSites, entity_id);
    }
    private void loadDataFlow() {
        this.CF.loadDataFlowMeasurements(tblFlow);
    }

    private void cbxEntity() {
        this.CU.loadEntityAdmin(cbxEntityUser, entity_id);
        this.CN.loadEntityAdmin(cbxEntityNascent, entity_id);
        this.CS.loadEntityAdmin(cbxEntitySites, entity_id);

    }
    private void cbxRoles() {
        boolean isAdmin = true; // Puedes ajustar este valor según tus necesidades.
        boolean isDigitador = false;
        this.CU.loadRole(cbxRole, isAdmin, isDigitador);
    }
    
     private void cbxsProvinces() {
        this.CS.loadProvince(cbxProvinceSites);
        this.CN.loadProvince(cbxProvinceNascent);
    }

    private void cbxsCantons(String provinceId) {
        this.CS.loadCanton(cbxCantonSites, provinceId);
    }
    private void cbxsCantons1(String provinceId) {
        this.CN.loadCanton(cbxCantonNascent, provinceId);
    }
     private void cbxsDistricts(String CantonID) {
        this.CS.loadDistrict(cbxDistrictSites,CantonID);
    }
    private void cbxsDistricts1(String CantonID) {
        this.CN.loadDistrict(cbxDistrictNascent,CantonID);
    }
    private void cbxsNascent() {
        this.CF.loadNascent(cbxNascentFlow);
    }
     private void cbxSampling(){
         this.CF.loadSampling(cbxSitesFlow);
     }
    private void clear(){
        this.CU.clearFields(txtNameUser, txtFirst_Name, txtSecond_Name, txtEmailUser, txtpassword);
        this.CN.clearFields(txtNameNascent, txtAddressNascent, txtLatitude, txtLength, txtDescriptionNascent);
        this.CS.ClearFields(txtNameSites);
        this.CF.clearFields(txtCapacity, txtMethod, txtObservation, txtDate);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabAdmNaciente = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtNameUser = new javax.swing.JTextField();
        txtFirst_Name = new javax.swing.JTextField();
        txtSecond_Name = new javax.swing.JTextField();
        txtEmailUser = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAddUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        cbxEntityUser = new javax.swing.JComboBox<>();
        cbxRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtAddressNascent = new javax.swing.JTextField();
        txtLatitude = new javax.swing.JTextField();
        txtLength = new javax.swing.JTextField();
        txtDescriptionNascent = new javax.swing.JTextField();
        cbxProvinceNascent = new javax.swing.JComboBox<>();
        cbxCantonNascent = new javax.swing.JComboBox<>();
        cbxDistrictNascent = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNascent = new javax.swing.JTable();
        btnAddNascent = new javax.swing.JButton();
        btnEditNascent = new javax.swing.JButton();
        btnDeleteNascent = new javax.swing.JButton();
        txtNameNascent = new javax.swing.JTextField();
        cbxEntityNascent = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtNameSites = new javax.swing.JTextField();
        cbxProvinceSites = new javax.swing.JComboBox<>();
        cbxCantonSites = new javax.swing.JComboBox<>();
        cbxDistrictSites = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSites = new javax.swing.JTable();
        btnAddSites = new javax.swing.JButton();
        btnEditSites = new javax.swing.JButton();
        btnDeleteSites = new javax.swing.JButton();
        cbxEntitySites = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtCapacity = new javax.swing.JTextField();
        txtMethod = new javax.swing.JTextField();
        txtObservation = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        cbxDone = new javax.swing.JComboBox<>();
        cbxNascentFlow = new javax.swing.JComboBox<>();
        cbxSitesFlow = new javax.swing.JComboBox<>();
        btnAddFlow = new javax.swing.JButton();
        btnEditFlow = new javax.swing.JButton();
        btnDeleteFlow = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFlow = new javax.swing.JTable();
        cbxWeather = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNameUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.add(txtNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 240, 50));

        txtFirst_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFirst_Name.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Primer Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.add(txtFirst_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 50));

        txtSecond_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSecond_Name.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Segundo Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.add(txtSecond_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, 50));

        txtEmailUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Correo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.add(txtEmailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 240, 50));

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 240, 50));

        tblUsers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Correo", "Contraseña", "Entidad", "Rol"
            }
        ));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 10, 960, 540));

        btnAddUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddUser.setText("Agregar");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 220, 49));

        btnEditUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditUser.setText("Editar");
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 100, 40));

        btnDeleteUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteUser.setText("Eliminar");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 100, 40));

        cbxEntityUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEntityUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxEntityUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Entity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxEntityUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEntityUserItemStateChanged(evt);
            }
        });
        jPanel2.add(cbxEntityUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 50));

        cbxRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxRole.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Rol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxRole.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxRoleItemStateChanged(evt);
            }
        });
        jPanel2.add(cbxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 240, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoUserAdm.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1330, 570));

        jTabAdmNaciente.addTab("Usuario", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAddressNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddressNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.add(txtAddressNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 49));

        txtLatitude.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLatitude.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Latitud", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.add(txtLatitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, 49));

        txtLength.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLength.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Longitud", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLengthActionPerformed(evt);
            }
        });
        jPanel3.add(txtLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, 49));

        txtDescriptionNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescriptionNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Descripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.add(txtDescriptionNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, 50));

        cbxProvinceNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxProvinceNascent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxProvinceNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Provincia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxProvinceNascent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProvinceNascentItemStateChanged(evt);
            }
        });
        cbxProvinceNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProvinceNascentActionPerformed(evt);
            }
        });
        jPanel3.add(cbxProvinceNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, 50));

        cbxCantonNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCantonNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cantón", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxCantonNascent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCantonNascentItemStateChanged(evt);
            }
        });
        cbxCantonNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantonNascentActionPerformed(evt);
            }
        });
        jPanel3.add(cbxCantonNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 190, 50));

        cbxDistrictNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxDistrictNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Distrito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxDistrictNascent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDistrictNascentItemStateChanged(evt);
            }
        });
        cbxDistrictNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDistrictNascentActionPerformed(evt);
            }
        });
        jPanel3.add(cbxDistrictNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 190, 50));

        tblNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNascent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Dirección", "Latitud", "Longitud", "Descripción", "Provincia", "Cantón", "Distrito", "Entity"
            }
        ));
        tblNascent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNascentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNascent);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 1020, 470));

        btnAddNascent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddNascent.setText("Agregar");
        btnAddNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNascentActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 150, 40));

        btnEditNascent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditNascent.setText("Editar");
        btnEditNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNascentActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 130, 40));

        btnDeleteNascent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteNascent.setText("Eliminar");
        btnDeleteNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNascentActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeleteNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 140, 40));

        txtNameNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtNameNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameNascentActionPerformed(evt);
            }
        });
        jPanel3.add(txtNameNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        cbxEntityNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEntityNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Entity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxEntityNascent.setPreferredSize(new java.awt.Dimension(71, 30));
        cbxEntityNascent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEntityNascentItemStateChanged(evt);
            }
        });
        cbxEntityNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntityNascentActionPerformed(evt);
            }
        });
        jPanel3.add(cbxEntityNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNascentAdm.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 560));

        jTabAdmNaciente.addTab("Naciente", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNameSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameSites.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.add(txtNameSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 189, 50));

        cbxProvinceSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxProvinceSites.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxProvinceSites.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Provincia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxProvinceSites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProvinceSitesItemStateChanged(evt);
            }
        });
        cbxProvinceSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProvinceSitesActionPerformed(evt);
            }
        });
        jPanel4.add(cbxProvinceSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 50));

        cbxCantonSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCantonSites.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cantón", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxCantonSites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCantonSitesItemStateChanged(evt);
            }
        });
        cbxCantonSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantonSitesActionPerformed(evt);
            }
        });
        jPanel4.add(cbxCantonSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, 50));

        cbxDistrictSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxDistrictSites.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Distrito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxDistrictSites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDistrictSitesItemStateChanged(evt);
            }
        });
        jPanel4.add(cbxDistrictSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 190, 50));

        tblSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Provincia", "Cantón", "Distrito", "Entity"
            }
        ));
        tblSites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSitesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSites);
        if (tblSites.getColumnModel().getColumnCount() > 0) {
            tblSites.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 12, 990, 540));

        btnAddSites.setText("Agregar");
        btnAddSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSitesActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 162, 54));

        btnEditSites.setText("Editar");
        btnEditSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSitesActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 162, 54));

        btnDeleteSites.setText("Eliminar");
        btnDeleteSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSitesActionPerformed(evt);
            }
        });
        jPanel4.add(btnDeleteSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 162, 54));

        cbxEntitySites.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Entity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxEntitySites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEntitySitesItemStateChanged(evt);
            }
        });
        jPanel4.add(cbxEntitySites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 190, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSitioDeMuestreoAdm.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1250, 570));

        jTabAdmNaciente.addTab("Stio de Muestreo", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCapacity.setEditable(false);
        txtCapacity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCapacity.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Capacidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.add(txtCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 49));

        txtMethod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMethod.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Metodo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.add(txtMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 50));

        txtObservation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtObservation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Observación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.add(txtObservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, 50));

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 240, 50));

        cbxDone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxDone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cbxDone.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Realizado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.add(cbxDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 240, 50));

        cbxNascentFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxNascentFlow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNascentFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Naciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxNascentFlow.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNascentFlowItemStateChanged(evt);
            }
        });
        jPanel5.add(cbxNascentFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 240, 50));

        cbxSitesFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxSitesFlow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSitesFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sitio de Muestreo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxSitesFlow.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSitesFlowItemStateChanged(evt);
            }
        });
        jPanel5.add(cbxSitesFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 240, 50));

        btnAddFlow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddFlow.setText("Agregar");
        btnAddFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlowActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 120, 50));

        btnEditFlow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditFlow.setText("Editar");
        btnEditFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFlowActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 105, 50));

        btnDeleteFlow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteFlow.setText("Eliminar");
        btnDeleteFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFlowActionPerformed(evt);
            }
        });
        jPanel5.add(btnDeleteFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 106, 50));

        tblFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblFlow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Capacidad", "Metodo", "Observación", "Fecha", "Clima", "Realizado", "Naciente", "Sitio de Muestreo"
            }
        ));
        tblFlow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFlowMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblFlow);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 11, 974, 480));

        cbxWeather.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxWeather.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soleado", "Lluvioso", "Nublado" }));
        cbxWeather.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Clima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.add(cbxWeather, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMedicionAdm.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 560));

        jTabAdmNaciente.addTab("Medición", jPanel5);

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(51, 255, 51));

        jMenu1.setBackground(new java.awt.Color(255, 0, 51));
        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setText("Reporte");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Reporte Grafico");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Atras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabAdmNaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 1236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabAdmNaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCantonSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantonSitesActionPerformed
        // TODO add your handling code here:
        String selectedCanton = (String) cbxCantonSites.getSelectedItem();
        String cantonId = this.CC.obtenerCanton(selectedCanton); // Debes implementar esta función para obtener el ID de la provincia seleccionada
        this.cbxsDistricts(cantonId);
    }//GEN-LAST:event_cbxCantonSitesActionPerformed

    private void txtNameNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameNascentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameNascentActionPerformed

    private void txtLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLengthActionPerformed

    private void cbxProvinceSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProvinceSitesActionPerformed
        // TODO add your handling code here:
        String selectedProvince = (String) cbxProvinceSites.getSelectedItem();
        String provinceId = this.CP.obtenerProvince(selectedProvince); // Debes implementar esta función para obtener el ID de la provincia seleccionada
        this.cbxsCantons(provinceId);
    }//GEN-LAST:event_cbxProvinceSitesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       // TODO add your handling code here:
        this.dispose();
        Account RE = new Account(this,true);
        RE.pack();
        RE.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login log = new Login();
        log.pack();
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnDeleteFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFlowActionPerformed
        // TODO add your handling code here:
        this.CF.deleteFlow();
        this.clear();
        this.loadDataFlow();
    }//GEN-LAST:event_btnDeleteFlowActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        this.CU.addUser(txtNameUser, txtFirst_Name, txtSecond_Name, txtEmailUser, txtpassword);
        this.clear();
        this.loadDataUser();
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
        this.CU.deleteUser();
        this.clear();
        this.loadDataUser();
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        // TODO add your handling code here:
        this.CU.updateUser(txtNameUser, txtFirst_Name, txtSecond_Name, txtEmailUser, txtpassword);
        this.clear();
        this.loadDataUser();
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void cbxEntityUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEntityUserItemStateChanged
        // TODO add your handling code here:
        this.CU.getIdEntity(cbxEntityUser);
    }//GEN-LAST:event_cbxEntityUserItemStateChanged

    private void cbxRoleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxRoleItemStateChanged
        // TODO add your handling code here:
        this.CU.getIdRole(cbxRole);
    }//GEN-LAST:event_cbxRoleItemStateChanged

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        // TODO add your handling code here:
        this.CU.selectedRow(tblUsers, txtNameUser, txtFirst_Name, txtSecond_Name, txtEmailUser, txtpassword, cbxEntityUser, cbxRole);
    }//GEN-LAST:event_tblUsersMouseClicked

    private void cbxDistrictNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDistrictNascentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDistrictNascentActionPerformed

    private void btnAddNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNascentActionPerformed
        // TODO add your handling code here:
        this.CN.addNascent(txtNameNascent, txtAddressNascent, txtLatitude, txtLength, txtDescriptionNascent);
        this.clear();
        this.loadDataNascent();
    }//GEN-LAST:event_btnAddNascentActionPerformed

    private void btnEditNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNascentActionPerformed
        // TODO add your handling code here:
        this.CN.UpdateNascent(txtNameNascent, txtAddressNascent, txtLatitude, txtLength, txtDescriptionNascent);
        this.clear();
        this.loadDataNascent();
    }//GEN-LAST:event_btnEditNascentActionPerformed

    private void btnDeleteNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNascentActionPerformed
        // TODO add your handling code here:
        this.CN.deleteNascent();
        this.clear();
        this.loadDataNascent();
    }//GEN-LAST:event_btnDeleteNascentActionPerformed

    private void cbxProvinceNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProvinceNascentActionPerformed
        // TODO add your handling code here:
         String selectedProvince = (String) cbxProvinceNascent.getSelectedItem();
        String provinceId = this.CP.obtenerProvince(selectedProvince); // Debes implementar esta función para obtener el ID de la provincia seleccionada
        this.cbxsCantons1(provinceId);
    }//GEN-LAST:event_cbxProvinceNascentActionPerformed

    private void cbxCantonNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantonNascentActionPerformed
        // TODO add your handling code here:
          String selectedCanton = (String) cbxCantonNascent.getSelectedItem();
        String cantonId = this.CC.obtenerCanton(selectedCanton); // Debes implementar esta función para obtener el ID de la provincia seleccionada
        this.cbxsDistricts1(cantonId);
    }//GEN-LAST:event_cbxCantonNascentActionPerformed

    private void cbxProvinceNascentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProvinceNascentItemStateChanged
        // TODO add your handling code here:
        this.CN.getIdProvince(cbxProvinceNascent);
    }//GEN-LAST:event_cbxProvinceNascentItemStateChanged

    private void cbxCantonNascentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCantonNascentItemStateChanged
        // TODO add your handling code here:
        this.CN.getIdCanton(cbxCantonNascent);
    }//GEN-LAST:event_cbxCantonNascentItemStateChanged

    private void cbxDistrictNascentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDistrictNascentItemStateChanged
        // TODO add your handling code here:
        this.CN.getIdDistrict(cbxDistrictNascent);
    }//GEN-LAST:event_cbxDistrictNascentItemStateChanged

    private void tblNascentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNascentMouseClicked
        // TODO add your handling code here:
        this.CN.selectedRow(tblNascent, txtNameNascent, txtAddressNascent, txtLatitude, txtLength, txtDescriptionNascent, cbxProvinceNascent, cbxCantonNascent, cbxDistrictNascent, cbxEntityNascent);
    }//GEN-LAST:event_tblNascentMouseClicked

    private void cbxEntityNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntityNascentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEntityNascentActionPerformed

    private void cbxEntityNascentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEntityNascentItemStateChanged
        // TODO add your handling code here:
        this.CN.getIdEntity(cbxEntityNascent);
    }//GEN-LAST:event_cbxEntityNascentItemStateChanged

    private void btnAddSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSitesActionPerformed
        // TODO add your handling code here:
        this.CS.addSamplingsite(txtNameSites);
        this.clear();
        this.loadDataSites();
    }//GEN-LAST:event_btnAddSitesActionPerformed

    private void btnEditSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSitesActionPerformed
        // TODO add your handling code here:
        this.CS.updateSamplingsite(txtNameSites);
        this.clear();
        this.loadDataSites();
    }//GEN-LAST:event_btnEditSitesActionPerformed

    private void btnDeleteSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSitesActionPerformed
        // TODO add your handling code here:
        this.CS.deleteSamplingsite();
        this.clear();
        this.loadDataSites();
    }//GEN-LAST:event_btnDeleteSitesActionPerformed

    private void cbxProvinceSitesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProvinceSitesItemStateChanged
        // TODO add your handling code here:
        this.CS.getIdProvince(cbxProvinceSites);
    }//GEN-LAST:event_cbxProvinceSitesItemStateChanged

    private void cbxCantonSitesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCantonSitesItemStateChanged
        // TODO add your handling code here:
        this.CS.getIdCanton(cbxCantonSites);
    }//GEN-LAST:event_cbxCantonSitesItemStateChanged

    private void cbxDistrictSitesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDistrictSitesItemStateChanged
        // TODO add your handling code here:
        this.CS.getIdDistrict(cbxDistrictSites);
    }//GEN-LAST:event_cbxDistrictSitesItemStateChanged

    private void cbxEntitySitesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEntitySitesItemStateChanged
        // TODO add your handling code here:
        this.CS.getIdEntity(cbxEntitySites);
    }//GEN-LAST:event_cbxEntitySitesItemStateChanged

    private void tblSitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSitesMouseClicked
        // TODO add your handling code here:
        this.CS.selectedRow(tblSites, txtNameSites, cbxProvinceSites, cbxCantonSites, cbxDistrictSites, cbxEntitySites);
    }//GEN-LAST:event_tblSitesMouseClicked

    private void btnAddFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlowActionPerformed
        // TODO add your handling code here:
        
        this.CF.addFlowMeasurement(txtMethod, txtObservation, cbxWeather, cbxDone);
        this.clear();
        this.loadDataFlow();
    }//GEN-LAST:event_btnAddFlowActionPerformed

    private void btnEditFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFlowActionPerformed
        // TODO add your handling code here:
       
        this.CF.updateflowMeasurement(txtCapacity, txtMethod, txtObservation, txtDate, cbxWeather, cbxDone);
        this.clear();
        this.loadDataFlow();
    }//GEN-LAST:event_btnEditFlowActionPerformed

    private void cbxNascentFlowItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNascentFlowItemStateChanged
        // TODO add your handling code here:
        this.CF.getIdNascent(cbxNascentFlow);
    }//GEN-LAST:event_cbxNascentFlowItemStateChanged

    private void cbxSitesFlowItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSitesFlowItemStateChanged
        // TODO add your handling code here:
        this.CF.getIdSampling(cbxSitesFlow);
    }//GEN-LAST:event_cbxSitesFlowItemStateChanged

    private void tblFlowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFlowMouseClicked
        // TODO add your handling code here:
        this.CF.selectedRow(tblFlow, txtCapacity, txtMethod, txtObservation, txtDate, cbxWeather, cbxDone, cbxNascentFlow, cbxSitesFlow);
    }//GEN-LAST:event_tblFlowMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Reportegrafica RG = new Reportegrafica(this,true);
        this.pack();
        RG.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFlow;
    private javax.swing.JButton btnAddNascent;
    private javax.swing.JButton btnAddSites;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDeleteFlow;
    private javax.swing.JButton btnDeleteNascent;
    private javax.swing.JButton btnDeleteSites;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditFlow;
    private javax.swing.JButton btnEditNascent;
    private javax.swing.JButton btnEditSites;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JComboBox<String> cbxCantonNascent;
    private javax.swing.JComboBox<String> cbxCantonSites;
    private javax.swing.JComboBox<String> cbxDistrictNascent;
    private javax.swing.JComboBox<String> cbxDistrictSites;
    private javax.swing.JComboBox<String> cbxDone;
    private javax.swing.JComboBox<String> cbxEntityNascent;
    private javax.swing.JComboBox<String> cbxEntitySites;
    private javax.swing.JComboBox<String> cbxEntityUser;
    private javax.swing.JComboBox<String> cbxNascentFlow;
    private javax.swing.JComboBox<String> cbxProvinceNascent;
    private javax.swing.JComboBox<String> cbxProvinceSites;
    private javax.swing.JComboBox<String> cbxRole;
    private javax.swing.JComboBox<String> cbxSitesFlow;
    private javax.swing.JComboBox<String> cbxWeather;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabAdmNaciente;
    private javax.swing.JTable tblFlow;
    private javax.swing.JTable tblNascent;
    private javax.swing.JTable tblSites;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtAddressNascent;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescriptionNascent;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtFirst_Name;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtMethod;
    private javax.swing.JTextField txtNameNascent;
    private javax.swing.JTextField txtNameSites;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JTextField txtObservation;
    private javax.swing.JTextField txtSecond_Name;
    private javax.swing.JTextField txtpassword;
    // End of variables declaration//GEN-END:variables

    
}
