package View;

import Controller.CTRLUser;
import Model.User;
import Model.UserDAO;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    CTRLUser CU = new CTRLUser();
    public Login() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextNameUser = new javax.swing.JTextField();
        jPasswordUser = new javax.swing.JPasswordField();
        jButtonStart = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 230, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jTextNameUser.setBackground(new java.awt.Color(0, 0, 51));
        jTextNameUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextNameUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextNameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 200, 30));

        jPasswordUser.setBackground(new java.awt.Color(51, 0, 51));
        jPasswordUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPasswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 200, 30));

        jButtonStart.setBackground(new java.awt.Color(0, 0, 255));
        jButtonStart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonStart.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStart.setText("Iniciar Sesion");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jLabelFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameUserActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String username = jTextNameUser.getText();
        String password = new String(jPasswordUser.getPassword()); // Get password as a String

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error:  Algun campo está vacío");
        } else {
            UserDAO userDAO = new UserDAO();
            User user = userDAO.getUserByUsername(username);

            if (user != null && user.getPassword().equals(password)) {
                //JOptionPane.showMessageDialog(null, "Inicio de secion correcto");

                // Determine which interface to open based on user's role_id
                int roleId = user.getRole_id();
                if (roleId == 1) {
                    // Open the Digitador interface
                    SuperAdministrator SAdm = new SuperAdministrator();
                    SAdm.setVisible(true);
                    this.dispose();
                } else if (roleId == 2) {
                    // Open the Administrator interface
                    int entity_id = user.getEntity_id();
                    Administrator adm = new Administrator(entity_id);
                    adm.setVisible(true);
                    /*int entity_id = user.getEntity_id(); // Supongamos que entity_id está disponible
                     // Reemplaza TuClase con el nombre de la clase que contiene loadDataUserAdmin
                    this.CU.loadDataUserAdmin(tblUsers, entity_id);*/
                    this.dispose();
                } else if (roleId == 3) {
                    // Open the Super Administrator interface
                    int userId = user.getId();
                    Typist digitador = new Typist(userId);
                    digitador.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Rol no es correcto");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto");
            }
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPasswordField jPasswordUser;
    private javax.swing.JTextField jTextNameUser;
    // End of variables declaration//GEN-END:variables

}
