package View;


import Controller.CTRLDistrict;
import Controller.CTRLUser;
import Controller.CTRLEntity;
import Controller.CTRLFlowMeasurement;
import Controller.CTRLNascent;
import Controller.CTRLSamplingsite;
import Model.CantonDAO;
import Model.ProvinceDAO;


public class SuperAdministrator extends javax.swing.JFrame {

    CTRLUser CU = new CTRLUser();
    CTRLEntity CE = new CTRLEntity();
    CTRLNascent CN = new CTRLNascent();
    CTRLFlowMeasurement CF= new CTRLFlowMeasurement();
    CTRLSamplingsite CS = new CTRLSamplingsite();
    ProvinceDAO CP = new ProvinceDAO();
    CantonDAO CC = new CantonDAO();
    CTRLDistrict CD = new CTRLDistrict();
    
    public SuperAdministrator() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listUser();
        this.listEntitys();
        this.listFlow();
        this.listNascent();
        this.listSites();
        this.cbxsEntitys();
        this.cbxsNascent();
        this.cbxSampling();
        this.cbxsProvinces();
        this.cbxroles();
        this.clear();
    }
    private void listUser() {
        this.CU.loadDataUser(tblUser);
    }
    private void listNascent(){    
        this.CN.loadDataNascent(tblNascent);
    }
    private void listSites(){    
        this.CS.loadDataSamplingsite(tblSites);
    }
    private void listFlow(){    
        this.CF.loadDataFlowMeasurements(tblFlow);
    }
    private void listEntitys(){
        this.CE.loadDataEntitys(tblEntitys);
    }
    
    private void cbxsEntitys(){
        this.CU.loadEntity(cbxEntityUser);
        this.CN.loadEntity(cbxEntityNascent);
        this.CS.loadEntity(cbxEntitySites);
    }
    private void cbxroles() {
        boolean isAdmin = false; // Puedes ajustar este valor según tus necesidades.
        boolean isDigitador = false;
        this.CU.loadRole(cbxRoleUser, isAdmin, isDigitador);
    }

    private void cbxsProvinces() {
        this.CS.loadProvince(cbxProvinceSites);
        this.CN.loadProvince(cbxProvinceNascent);
    }

    private void cbxsCantons(String provinceId) {
        this.CS.loadCanton(cbxCantonSites, provinceId);
    }
    private void cbxsCantons1(String provinceId) {
        this.CN.loadCanton(cbxCantonNascent, provinceId);
    }

    private void cbxsDistricts(String CantonID) {
        this.CS.loadDistrict(cbxDistrictSites,CantonID);
    }
    private void cbxsDistricts1(String CantonID) {
        this.CN.loadDistrict(cbxDistrictNascent,CantonID);
    }
     private void cbxsNascent() {
        this.CF.loadNascent(cbxNascentFlow);
    }
     private void cbxSampling(){
         this.CF.loadSampling(cbxSitesFlow);
     }
    
    
    private void clear() {
        this.CU.clearFields(txtNameUser, txFirstnameUser, txtSecondnameUser, txtEmailUser, txtPasswordUser);
        this.CE.clearFields(txtLegalIDEntity, txtNameEntity, txtEmailEntity, txtTelephoneEntity, txtAddressEntity, txtDescriptionEntity);
        this.CF.clearFields(txtCapacityFlow, txtMethodFlow, txtObservationFlow, txtDateFlow);
        this.CN.clearFields(txtNameNascent, txtAddressNascent, txtLatitudeNascent, txtLengthNascent, txtDescriptionNascent);
        this.CS.ClearFields(txtNameSites);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jTextField2 = new javax.swing.JTextField();
        jTabUser = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtNameUser = new javax.swing.JTextField();
        txtPasswordUser = new javax.swing.JTextField();
        txFirstnameUser = new javax.swing.JTextField();
        txtSecondnameUser = new javax.swing.JTextField();
        txtEmailUser = new javax.swing.JTextField();
        cbxRoleUser = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        btnAddUser = new javax.swing.JButton();
        cbxEntityUser = new javax.swing.JComboBox<>();
        btnEditUser = new javax.swing.JButton();
        btnEliminateUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtLegalIDEntity = new javax.swing.JTextField();
        txtNameEntity = new javax.swing.JTextField();
        txtEmailEntity = new javax.swing.JTextField();
        txtTelephoneEntity = new javax.swing.JTextField();
        txtAddressEntity = new javax.swing.JTextField();
        txtDescriptionEntity = new javax.swing.JTextField();
        btnAddEntity = new javax.swing.JButton();
        btnEditEntity = new javax.swing.JButton();
        btnDeleteEntity = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEntitys = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonExitSamplingSite = new javax.swing.JButton();
        txtNameSites = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSites = new javax.swing.JTable();
        cbxProvinceSites = new javax.swing.JComboBox<>();
        cbxCantonSites = new javax.swing.JComboBox<>();
        cbxDistrictSites = new javax.swing.JComboBox<>();
        cbxEntitySites = new javax.swing.JComboBox<>();
        btnAddSites = new javax.swing.JButton();
        btnEditSites = new javax.swing.JButton();
        btnDeleteSites = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtAddressNascent = new javax.swing.JTextField();
        txtLengthNascent = new javax.swing.JTextField();
        cbxProvinceNascent = new javax.swing.JComboBox<>();
        cbxCantonNascent = new javax.swing.JComboBox<>();
        cbxDistrictNascent = new javax.swing.JComboBox<>();
        cbxEntityNascent = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNascent = new javax.swing.JTable();
        btnAddNascent = new javax.swing.JButton();
        btnDeleteNascent = new javax.swing.JButton();
        btnEditNascent = new javax.swing.JButton();
        jButtonExitNascent = new javax.swing.JButton();
        txtDescriptionNascent = new javax.swing.JTextField();
        txtLatitudeNascent = new javax.swing.JTextField();
        txtNameNascent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonExtitMeasurement = new javax.swing.JButton();
        txtCapacityFlow = new javax.swing.JTextField();
        txtMethodFlow = new javax.swing.JTextField();
        txtObservationFlow = new javax.swing.JTextField();
        txtDateFlow = new javax.swing.JTextField();
        cbxDoneFlow = new javax.swing.JComboBox<>();
        cbxNascentFlow = new javax.swing.JComboBox<>();
        cbxSitesFlow = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFlow = new javax.swing.JTable();
        btnAddFlow = new javax.swing.JButton();
        btnEditFlow = new javax.swing.JButton();
        btnDeleteFlow = new javax.swing.JButton();
        cbxWeatherFlow = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jTabUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNameUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.add(txtNameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 53));

        txtPasswordUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.add(txtPasswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 54));

        txFirstnameUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Primer Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txFirstnameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFirstnameUserActionPerformed(evt);
            }
        });
        jPanel2.add(txFirstnameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 53));

        txtSecondnameUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSecondnameUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Segundo Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.add(txtSecondnameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 53));

        txtEmailUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.add(txtEmailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 200, 54));

        cbxRoleUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxRoleUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxRoleUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Rol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxRoleUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxRoleUserItemStateChanged(evt);
            }
        });
        cbxRoleUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRoleUserActionPerformed(evt);
            }
        });
        jPanel2.add(cbxRoleUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 50));

        jToolBar1.setRollover(true);
        jPanel2.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 133, -1, -1));

        btnAddUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddUser.setText("Agregar");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, 50));

        cbxEntityUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEntityUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxEntityUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Entidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxEntityUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEntityUserItemStateChanged(evt);
            }
        });
        cbxEntityUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntityUserActionPerformed(evt);
            }
        });
        jPanel2.add(cbxEntityUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 50));

        btnEditUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditUser.setText("Editar");
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 90, 30));

        btnEliminateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminateUser.setText("Eliminar");
        btnEliminateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminateUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 490, -1, 30));

        tblUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Correo", "Contraseña", "Entidad", "Rol"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 29, 994, 480));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TabFondoUser.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 530));

        jTabUser.addTab("Usuario", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLegalIDEntity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLegalIDEntity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula Juridica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.add(txtLegalIDEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 200, 49));

        txtNameEntity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameEntity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.add(txtNameEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 67, 200, 49));

        txtEmailEntity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailEntity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.add(txtEmailEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 128, 200, 49));

        txtTelephoneEntity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelephoneEntity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.add(txtTelephoneEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, 50));

        txtAddressEntity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddressEntity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.add(txtAddressEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 190, 49));

        txtDescriptionEntity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescriptionEntity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.add(txtDescriptionEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, 49));

        btnAddEntity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddEntity.setText("Añadir");
        btnAddEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEntityActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 190, 50));

        btnEditEntity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditEntity.setText("Editar");
        btnEditEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEntityActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 90, 50));

        btnDeleteEntity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteEntity.setText("Eliminar");
        btnDeleteEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEntityActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeleteEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 100, 50));

        tblEntitys.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblEntitys.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cedula Juridica", "Nombre", "Email", "Telefono", "Dirección ", "Descripción"
            }
        ));
        tblEntitys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntitysMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEntitys);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 45, 1010, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoEntitySA.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        jTabUser.addTab("Entidad", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExitSamplingSite.setText("Salir");
        jButtonExitSamplingSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitSamplingSiteActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonExitSamplingSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(1395, 6, -1, -1));

        txtNameSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameSites.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.add(txtNameSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 236, 56));

        tblSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Provincia", "Canton", "Distrito", "Entidad"
            }
        ));
        tblSites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSitesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSites);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 960, 458));

        cbxProvinceSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxProvinceSites.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Provincia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxProvinceSites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProvinceSitesItemStateChanged(evt);
            }
        });
        cbxProvinceSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProvinceSitesActionPerformed(evt);
            }
        });
        jPanel5.add(cbxProvinceSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, 50));

        cbxCantonSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCantonSites.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Canton", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxCantonSites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCantonSitesItemStateChanged(evt);
            }
        });
        cbxCantonSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantonSitesActionPerformed(evt);
            }
        });
        jPanel5.add(cbxCantonSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, 50));

        cbxDistrictSites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxDistrictSites.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Distrito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxDistrictSites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDistrictSitesItemStateChanged(evt);
            }
        });
        jPanel5.add(cbxDistrictSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 230, 50));

        cbxEntitySites.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEntitySites.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Entidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxEntitySites.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEntitySitesItemStateChanged(evt);
            }
        });
        jPanel5.add(cbxEntitySites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 230, 50));

        btnAddSites.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddSites.setText("Agregar");
        btnAddSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSitesActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, 50));

        btnEditSites.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditSites.setText("Editar");
        btnEditSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSitesActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, 40));

        btnDeleteSites.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteSites.setText("Eliminar");
        btnDeleteSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSitesActionPerformed(evt);
            }
        });
        jPanel5.add(btnDeleteSites, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSamplingSitesSA.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 530));

        jTabUser.addTab("Sitio de muestreo", jPanel5);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAddressNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddressNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Direccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.add(txtAddressNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 40));

        txtLengthNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLengthNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Longitud", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.add(txtLengthNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 40));

        cbxProvinceNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxProvinceNascent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxProvinceNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Provincia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxProvinceNascent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProvinceNascentItemStateChanged(evt);
            }
        });
        cbxProvinceNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProvinceNascentActionPerformed(evt);
            }
        });
        jPanel4.add(cbxProvinceNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 180, 50));

        cbxCantonNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCantonNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Canton", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxCantonNascent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCantonNascentItemStateChanged(evt);
            }
        });
        cbxCantonNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCantonNascentActionPerformed(evt);
            }
        });
        jPanel4.add(cbxCantonNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 180, 50));

        cbxDistrictNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxDistrictNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Distrito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxDistrictNascent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxDistrictNascentItemStateChanged(evt);
            }
        });
        cbxDistrictNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDistrictNascentActionPerformed(evt);
            }
        });
        jPanel4.add(cbxDistrictNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, 50));

        cbxEntityNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEntityNascent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxEntityNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Entidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxEntityNascent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxEntityNascentItemStateChanged(evt);
            }
        });
        cbxEntityNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntityNascentActionPerformed(evt);
            }
        });
        jPanel4.add(cbxEntityNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 180, 50));

        tblNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNascent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Direccion", "Latitud", "Longitud", "Descripcion", "Provincia", "Canton", "Distrito", "Entidad"
            }
        ));
        tblNascent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNascentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNascent);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 1010, 426));

        btnAddNascent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddNascent.setText("Añadir");
        btnAddNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNascentActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 120, 40));

        btnDeleteNascent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteNascent.setText("Eliminar");
        btnDeleteNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNascentActionPerformed(evt);
            }
        });
        jPanel4.add(btnDeleteNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 130, 40));

        btnEditNascent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditNascent.setText("Editar");
        btnEditNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNascentActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 120, 40));

        jButtonExitNascent.setText("Salir");
        jButtonExitNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitNascentActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonExitNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1401, 0, -1, -1));

        txtDescriptionNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescriptionNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.add(txtDescriptionNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 40));

        txtLatitudeNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Latitud", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.add(txtLatitudeNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 40));

        txtNameNascent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameNascent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtNameNascent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameNascentActionPerformed(evt);
            }
        });
        jPanel4.add(txtNameNascent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNascent.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1240, 530));

        jTabUser.addTab("Naciente", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExtitMeasurement.setText("Salir");
        jButtonExtitMeasurement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtitMeasurementActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonExtitMeasurement, new org.netbeans.lib.awtextra.AbsoluteConstraints(1401, 0, -1, -1));

        txtCapacityFlow.setEditable(false);
        txtCapacityFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCapacityFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Capacidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.add(txtCapacityFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 220, 49));

        txtMethodFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMethodFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Metodo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.add(txtMethodFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, 220, 48));

        txtObservationFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtObservationFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Observación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtObservationFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservationFlowActionPerformed(evt);
            }
        });
        jPanel6.add(txtObservationFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 115, 220, 49));

        txtDateFlow.setEditable(false);
        txtDateFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDateFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.add(txtDateFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 170, 220, 49));

        cbxDoneFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxDoneFlow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cbxDoneFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Realizado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.add(cbxDoneFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, 50));

        cbxNascentFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxNascentFlow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNascentFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Naciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxNascentFlow.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNascentFlowItemStateChanged(evt);
            }
        });
        jPanel6.add(cbxNascentFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 220, 50));

        cbxSitesFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxSitesFlow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxSitesFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sitio de muestreo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        cbxSitesFlow.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSitesFlowItemStateChanged(evt);
            }
        });
        jPanel6.add(cbxSitesFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 220, 50));

        tblFlow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Capacidad", "Metodo", "Obsevación", "Fecha", "Clima", "Realizacido", "Naciente", "Sitio de Muestreo "
            }
        ));
        tblFlow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFlowMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblFlow);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 970, 410));

        btnAddFlow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddFlow.setText("Agregar");
        btnAddFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlowActionPerformed(evt);
            }
        });
        jPanel6.add(btnAddFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 150, 50));

        btnEditFlow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditFlow.setText("Editar");
        btnEditFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFlowActionPerformed(evt);
            }
        });
        jPanel6.add(btnEditFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 110, 50));

        btnDeleteFlow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteFlow.setText("Eliminar");
        btnDeleteFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFlowActionPerformed(evt);
            }
        });
        jPanel6.add(btnDeleteFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 100, 50));

        cbxWeatherFlow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxWeatherFlow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soleado", "Lluvioso", "Nublado" }));
        cbxWeatherFlow.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Clima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.add(cbxWeatherFlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 220, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMeasurements.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -160, -1, 690));

        jTabUser.addTab("Medición", jPanel6);

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(153, 255, 255));

        jMenu3.setForeground(new java.awt.Color(0, 0, 255));
        jMenu3.setText("Menu");
        jMenu3.setFocusTraversalPolicyProvider(true);
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setText("Reportes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem4.setText("Reporte Grafico");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem2.setText("Atras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabUser, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  ////////
    private void btnEditEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEntityActionPerformed
        // TODO add your handling code here:
        this.CE.updateEntity(txtLegalIDEntity, txtNameEntity, txtEmailEntity, txtTelephoneEntity, txtAddressEntity, txtDescriptionEntity);
        this.clear();
        this.listEntitys();
    }//GEN-LAST:event_btnEditEntityActionPerformed

    private void btnAddEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEntityActionPerformed
        // TODO add your handling code here:
        this.CE.addEntity(txtLegalIDEntity, txtNameEntity, txtEmailEntity, txtTelephoneEntity, txtAddressEntity, txtDescriptionEntity);
        this.clear();
        this.listEntitys();
    }//GEN-LAST:event_btnAddEntityActionPerformed

    private void cbxEntityUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntityUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEntityUserActionPerformed

    private void txFirstnameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFirstnameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFirstnameUserActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        this.CU.addUser(txtNameUser, txFirstnameUser, txtSecondnameUser, txtEmailUser, txtPasswordUser);
        this.clear();
        this.listUser();
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void jButtonExitNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitNascentActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jButtonExitNascentActionPerformed

    private void jButtonExitSamplingSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitSamplingSiteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jButtonExitSamplingSiteActionPerformed

    private void jButtonExtitMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtitMeasurementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jButtonExtitMeasurementActionPerformed

    private void cbxRoleUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRoleUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRoleUserActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
        this.CU.selectedRow(tblUser, txtNameUser, txFirstnameUser, txtSecondnameUser, txtEmailUser, txtPasswordUser, cbxEntityUser, cbxRoleUser);
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        // TODO add your handling code here:
        this.CU.updateUser(txtNameUser, txFirstnameUser, txtSecondnameUser, txtEmailUser, txtPasswordUser);
        this.clear();
        this.listUser();
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnEliminateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminateUserActionPerformed
        // TODO add your handling code here:
        this.CU.deleteUser();
        this.clear();
        this.listUser();
    }//GEN-LAST:event_btnEliminateUserActionPerformed

    private void cbxEntityUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEntityUserItemStateChanged
        // TODO add your handling code here:
        this.CU.getIdEntity(cbxEntityUser);
    }//GEN-LAST:event_cbxEntityUserItemStateChanged

    private void cbxRoleUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxRoleUserItemStateChanged
        // TODO add your handling code here:
        this.CU.getIdRole(cbxRoleUser);
    }//GEN-LAST:event_cbxRoleUserItemStateChanged

    private void btnEditSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSitesActionPerformed
        // TODO add your handling code here:
        this.CS.updateSamplingsite(txtNameSites);
        this.clear();
        this.listSites();
    }//GEN-LAST:event_btnEditSitesActionPerformed

    private void btnDeleteEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEntityActionPerformed
        // TODO add your handling code here:
        this.CE.deleteEntity();
        this.clear();
        this.listEntitys();
    }//GEN-LAST:event_btnDeleteEntityActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Account RE = new Account(this,true);
        this.pack();
        RE.setVisible(true);        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login log = new Login();
        this.pack();
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cbxEntityNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntityNascentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEntityNascentActionPerformed

    private void txtNameNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameNascentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameNascentActionPerformed

    private void txtObservationFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservationFlowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservationFlowActionPerformed

    private void cbxProvinceSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProvinceSitesActionPerformed
        // TODO add your handling code here:
       String selectedProvince = (String) cbxProvinceSites.getSelectedItem();
        String provinceId = this.CP.obtenerProvince(selectedProvince); // Debes implementar esta función para obtener el ID de la provincia seleccionada
        this.cbxsCantons(provinceId);
                
    }//GEN-LAST:event_cbxProvinceSitesActionPerformed

    private void cbxCantonSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantonSitesActionPerformed
        // TODO add your handling code here:
        String selectedCanton = (String) cbxCantonSites.getSelectedItem();
        String cantonId = this.CC.obtenerCanton(selectedCanton); // Debes implementar esta función para obtener el ID de la provincia seleccionada
        this.cbxsDistricts(cantonId);
    }//GEN-LAST:event_cbxCantonSitesActionPerformed

    private void cbxProvinceNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProvinceNascentActionPerformed
        // TODO add your handling code here:
        String selectedProvince = (String) cbxProvinceNascent.getSelectedItem();
        String provinceId = this.CP.obtenerProvince(selectedProvince); // Debes implementar esta función para obtener el ID de la provincia seleccionada
        this.cbxsCantons1(provinceId);
    }//GEN-LAST:event_cbxProvinceNascentActionPerformed

    private void cbxCantonNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCantonNascentActionPerformed
        // TODO add your handling code here:
         String selectedCanton = (String) cbxCantonNascent.getSelectedItem();
        String cantonId = this.CC.obtenerCanton(selectedCanton); // Debes implementar esta función para obtener el ID de la provincia seleccionada
        this.cbxsDistricts1(cantonId);
    }//GEN-LAST:event_cbxCantonNascentActionPerformed

    private void tblEntitysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntitysMouseClicked
        // TODO add your handling code here:
        this.CE.selectedRow(tblEntitys, txtLegalIDEntity, txtNameEntity, txtEmailEntity, txtTelephoneEntity, txtAddressEntity, txtDescriptionEntity);
    }//GEN-LAST:event_tblEntitysMouseClicked

    private void btnAddSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSitesActionPerformed
        // TODO add your handling code here:
        this.CS.addSamplingsite(txtNameSites);
        this.clear();
        this.listSites();
    }//GEN-LAST:event_btnAddSitesActionPerformed

    private void btnDeleteSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSitesActionPerformed
        // TODO add your handling code here:
        this.CS.deleteSamplingsite();
        this.clear();
        this.listSites();
    }//GEN-LAST:event_btnDeleteSitesActionPerformed

    private void tblSitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSitesMouseClicked
        // TODO add your handling code here:
        this.CS.selectedRow(tblSites, txtNameSites, cbxProvinceSites, cbxCantonSites, cbxDistrictSites, cbxEntitySites);
    }//GEN-LAST:event_tblSitesMouseClicked

    private void cbxProvinceSitesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProvinceSitesItemStateChanged
        // TODO add your handling code here:
        this.CS.getIdProvince(cbxProvinceSites);
    }//GEN-LAST:event_cbxProvinceSitesItemStateChanged

    private void cbxCantonSitesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCantonSitesItemStateChanged
        // TODO add your handling code here:
        /*this.CS.getIdCanton(cbxCantonSites);*/
       this.CS.getIdCanton(cbxCantonSites);
    }//GEN-LAST:event_cbxCantonSitesItemStateChanged

    private void cbxDistrictSitesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDistrictSitesItemStateChanged
        // TODO add your handling code here:
        this.CS.getIdDistrict(cbxDistrictSites);
    }//GEN-LAST:event_cbxDistrictSitesItemStateChanged

    private void cbxEntitySitesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEntitySitesItemStateChanged
        // TODO add your handling code here:
        this.CS.getIdEntity(cbxEntitySites);
    }//GEN-LAST:event_cbxEntitySitesItemStateChanged

    private void btnAddNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNascentActionPerformed
        // TODO add your handling code here:
        this.CN.addNascent(txtNameNascent, txtAddressNascent, txtLatitudeNascent, txtLengthNascent, txtDescriptionNascent);
        this.clear();
        this.listNascent();
    }//GEN-LAST:event_btnAddNascentActionPerformed

    private void btnEditNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNascentActionPerformed
        // TODO add your handling code here:
        this.CN.UpdateNascent(txtNameNascent, txtAddressNascent, txtLatitudeNascent, txtLengthNascent, txtDescriptionNascent);
        this.clear();
        this.listNascent();
    }//GEN-LAST:event_btnEditNascentActionPerformed

    private void btnDeleteNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNascentActionPerformed
        // TODO add your handling code here:
        this.CN.deleteNascent();
        this.clear();
        this.listNascent();
    }//GEN-LAST:event_btnDeleteNascentActionPerformed

    private void cbxProvinceNascentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProvinceNascentItemStateChanged
        // TODO add your handling code here:
        this.CN.getIdProvince(cbxProvinceNascent);
    }//GEN-LAST:event_cbxProvinceNascentItemStateChanged

    private void cbxCantonNascentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCantonNascentItemStateChanged
        // TODO add your handling code here:
        this.CN.getIdCanton(cbxCantonNascent);
    }//GEN-LAST:event_cbxCantonNascentItemStateChanged

    private void cbxDistrictNascentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxDistrictNascentItemStateChanged
        // TODO add your handling code here:
        this.CN.getIdDistrict(cbxDistrictNascent);
    }//GEN-LAST:event_cbxDistrictNascentItemStateChanged

    private void cbxEntityNascentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxEntityNascentItemStateChanged
        // TODO add your handling code here:
        this.CN.getIdEntity(cbxEntityNascent);
    }//GEN-LAST:event_cbxEntityNascentItemStateChanged

    private void tblNascentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNascentMouseClicked
        // TODO add your handling code here:
        this.CN.selectedRow(tblNascent, txtNameNascent, txtAddressNascent, txtLatitudeNascent, txtLengthNascent, txtDescriptionNascent, cbxProvinceNascent, cbxCantonNascent, cbxDistrictNascent, cbxEntityNascent);
    }//GEN-LAST:event_tblNascentMouseClicked

    private void btnAddFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlowActionPerformed
        // TODO add your handling code here:
        this.CF.addFlowMeasurement(txtMethodFlow, txtObservationFlow, cbxWeatherFlow, cbxDoneFlow);
        this.clear();
        this.listFlow();
    }//GEN-LAST:event_btnAddFlowActionPerformed

    private void btnEditFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFlowActionPerformed
        // TODO add your handling code here:
        this.CF.updateflowMeasurement(txtCapacityFlow, txtMethodFlow, txtObservationFlow, txtDateFlow, cbxWeatherFlow, cbxDoneFlow);
        this.clear();
        this.listFlow();
    }//GEN-LAST:event_btnEditFlowActionPerformed

    private void btnDeleteFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFlowActionPerformed
        // TODO add your handling code here:
        this.CF.deleteFlow();
        this.clear();
        this.listFlow();
    }//GEN-LAST:event_btnDeleteFlowActionPerformed

    private void tblFlowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFlowMouseClicked
        // TODO add your handling code here:
        this.CF.selectedRow(tblFlow, txtCapacityFlow, txtMethodFlow, txtObservationFlow, txtDateFlow, cbxWeatherFlow, cbxDoneFlow, cbxNascentFlow, cbxSitesFlow);
    }//GEN-LAST:event_tblFlowMouseClicked

    private void cbxDistrictNascentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDistrictNascentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDistrictNascentActionPerformed

    private void cbxSitesFlowItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSitesFlowItemStateChanged
        // TODO add your handling code here:
        this.CF.getIdSampling(cbxSitesFlow);
    }//GEN-LAST:event_cbxSitesFlowItemStateChanged

    private void cbxNascentFlowItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNascentFlowItemStateChanged
        // TODO add your handling code here:
        this.CF.getIdNascent(cbxNascentFlow);
    }//GEN-LAST:event_cbxNascentFlowItemStateChanged

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Reportegrafica RG = new Reportegrafica(this,true);
        this.pack();
        RG.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEntity;
    private javax.swing.JButton btnAddFlow;
    private javax.swing.JButton btnAddNascent;
    private javax.swing.JButton btnAddSites;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDeleteEntity;
    private javax.swing.JButton btnDeleteFlow;
    private javax.swing.JButton btnDeleteNascent;
    private javax.swing.JButton btnDeleteSites;
    private javax.swing.JButton btnEditEntity;
    private javax.swing.JButton btnEditFlow;
    private javax.swing.JButton btnEditNascent;
    private javax.swing.JButton btnEditSites;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnEliminateUser;
    private javax.swing.JComboBox<String> cbxCantonNascent;
    private javax.swing.JComboBox<String> cbxCantonSites;
    private javax.swing.JComboBox<String> cbxDistrictNascent;
    private javax.swing.JComboBox<String> cbxDistrictSites;
    private javax.swing.JComboBox<String> cbxDoneFlow;
    private javax.swing.JComboBox<String> cbxEntityNascent;
    private javax.swing.JComboBox<String> cbxEntitySites;
    private javax.swing.JComboBox<String> cbxEntityUser;
    private javax.swing.JComboBox<String> cbxNascentFlow;
    private javax.swing.JComboBox<String> cbxProvinceNascent;
    private javax.swing.JComboBox<String> cbxProvinceSites;
    private javax.swing.JComboBox<String> cbxRoleUser;
    private javax.swing.JComboBox<String> cbxSitesFlow;
    private javax.swing.JComboBox<String> cbxWeatherFlow;
    private javax.swing.JButton jButtonExitNascent;
    private javax.swing.JButton jButtonExitSamplingSite;
    private javax.swing.JButton jButtonExtitMeasurement;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabUser;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblEntitys;
    private javax.swing.JTable tblFlow;
    private javax.swing.JTable tblNascent;
    private javax.swing.JTable tblSites;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txFirstnameUser;
    private javax.swing.JTextField txtAddressEntity;
    private javax.swing.JTextField txtAddressNascent;
    private javax.swing.JTextField txtCapacityFlow;
    private javax.swing.JTextField txtDateFlow;
    private javax.swing.JTextField txtDescriptionEntity;
    private javax.swing.JTextField txtDescriptionNascent;
    private javax.swing.JTextField txtEmailEntity;
    private javax.swing.JTextField txtEmailUser;
    private javax.swing.JTextField txtLatitudeNascent;
    private javax.swing.JTextField txtLegalIDEntity;
    private javax.swing.JTextField txtLengthNascent;
    private javax.swing.JTextField txtMethodFlow;
    private javax.swing.JTextField txtNameEntity;
    private javax.swing.JTextField txtNameNascent;
    private javax.swing.JTextField txtNameSites;
    private javax.swing.JTextField txtNameUser;
    private javax.swing.JTextField txtObservationFlow;
    private javax.swing.JTextField txtPasswordUser;
    private javax.swing.JTextField txtSecondnameUser;
    private javax.swing.JTextField txtTelephoneEntity;
    // End of variables declaration//GEN-END:variables
}
